CREATE TABLE IF NOT EXISTS `vtec_plzgrp` (
  
  `VTECPLZ` varchar(6) CHARACTER SET utf8 NOT NULL UNIQUE,
  `VTECORT` varchar(50) CHARACTER SET utf8 NOT NULL,
  `VTECKANTON` varchar (50) CHARACTER SET utf8 NOT NULL,
  `VTECLIEFERN` varchar(250) CHARACTER SET utf8 NOT NULL,
  `VTECGRPA` TINYINT (2) NOT NULL,
  `VTECGRPB` TINYINT (2) NOT NULL,
  PRIMARY KEY (`VTECPLZ`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
